insert into products (`name`, `purchase_price`, `sale_price`) values ('Sprouts - Baby Pea Tendrils', 38.75, 70.17);
insert into products (`name`, `purchase_price`, `sale_price`) values ('Beer - Camerons Cream Ale', 70.43, 33.84);
insert into products (`name`, `purchase_price`, `sale_price`) values ('Beer - Sleeman Fine Porter', 32.11, 45.35);
insert into products (`name`, `purchase_price`, `sale_price`) values ('Pastrami', 49.76, 43.7);
insert into products (`name`, `purchase_price`, `sale_price`) values ('Energy - Boo - Koo', 50.54, 89.68);
insert into products (`name`, `purchase_price`, `sale_price`) values ('Pasta - Tortellini, Fresh', 44.55, 89.6);
insert into products (`name`, `purchase_price`, `sale_price`) values ('Ham - Cooked Italian', 35.14, 70.09);
insert into products (`name`, `purchase_price`, `sale_price`) values ('Spring Roll Wrappers', 78.3, 69.21);
insert into products (`name`, `purchase_price`, `sale_price`) values ('Mustard - Individual Pkg', 23.92, 73.14);
insert into products (`name`, `purchase_price`, `sale_price`) values ('Sugar - Monocystal / Rock', 79.41, 41.8);
insert into products (`name`, `purchase_price`, `sale_price`) values ('Wine - Ruffino Chianti Classico', 76.05, 64.89);
insert into products (`name`, `purchase_price`, `sale_price`) values ('Sherry - Dry', 60.99, 34.24);
insert into products (`name`, `purchase_price`, `sale_price`) values ('Dc - Sakura Fu', 55.95, 60.57);
insert into products (`name`, `purchase_price`, `sale_price`) values ('Cheese - Shred Cheddar / Mozza', 23.27, 90.7);
insert into products (`name`, `purchase_price`, `sale_price`) values ('Tea - English Breakfast', 22.63, 63.79);
insert into products (`name`, `purchase_price`, `sale_price`) values ('Puree - Raspberry', 37.47, 62.11);
insert into products (`name`, `purchase_price`, `sale_price`) values ('Clams - Canned', 58.71, 86.09);
insert into products (`name`, `purchase_price`, `sale_price`) values ('Temperature Recording Station', 31.64, 46.56);
insert into products (`name`, `purchase_price`, `sale_price`) values ('Stock - Fish', 67.33, 70.47);
insert into products (`name`, `purchase_price`, `sale_price`) values ('Wine - Sake', 75.29, 61.3);
insert into products (`name`, `purchase_price`, `sale_price`) values ('Cookie Chocolate Chip With', 47.81, 37.75);
insert into products (`name`, `purchase_price`, `sale_price`) values ('Peas - Pigeon, Dry', 47.7, 84.59);
insert into products (`name`, `purchase_price`, `sale_price`) values ('Rolled Oats', 44.6, 61.94);
insert into products (`name`, `purchase_price`, `sale_price`) values ('Cheese - Provolone', 45.35, 56.51);
insert into products (`name`, `purchase_price`, `sale_price`) values ('Pepper - Green', 25.52, 97.65);
insert into products (`name`, `purchase_price`, `sale_price`) values ('Flour - Strong', 29.66, 49.16);
insert into products (`name`, `purchase_price`, `sale_price`) values ('Scallops - 10/20', 79.98, 63.31);
insert into products (`name`, `purchase_price`, `sale_price`) values ('Bacardi Mojito', 49.06, 63.91);
insert into products (`name`, `purchase_price`, `sale_price`) values ('Duck - Fat', 59.15, 98.41);
insert into products (`name`, `purchase_price`, `sale_price`) values ('Cherries - Bing, Canned', 76.53, 99.89);
insert into products (`name`, `purchase_price`, `sale_price`) values ('Wine - Red, Lurton Merlot De', 30.17, 47.74);
insert into products (`name`, `purchase_price`, `sale_price`) values ('Paste - Black Olive', 23.46, 33.57);
insert into products (`name`, `purchase_price`, `sale_price`) values ('Pepper - Red Thai', 51.43, 90.18);
insert into products (`name`, `purchase_price`, `sale_price`) values ('Crackers - Trio', 59.44, 90.83);
insert into products (`name`, `purchase_price`, `sale_price`) values ('Hummus - Spread', 39.33, 31.17);
insert into products (`name`, `purchase_price`, `sale_price`) values ('Quail - Jumbo Boneless', 78.47, 48.44);
insert into products (`name`, `purchase_price`, `sale_price`) values ('Flower - Carnations', 41.13, 44.6);
insert into products (`name`, `purchase_price`, `sale_price`) values ('Dill - Primerba, Paste', 60.79, 54.93);
insert into products (`name`, `purchase_price`, `sale_price`) values ('Squid Ink', 20.51, 69.53);
insert into products (`name`, `purchase_price`, `sale_price`) values ('Pork - Caul Fat', 21.42, 34.95);
insert into products (`name`, `purchase_price`, `sale_price`) values ('Anisette - Mcguiness', 23.33, 70.49);
insert into products (`name`, `purchase_price`, `sale_price`) values ('Pumpkin - Seed', 74.93, 44.04);
insert into products (`name`, `purchase_price`, `sale_price`) values ('Ecolab - Power Fusion', 55.03, 30.67);
insert into products (`name`, `purchase_price`, `sale_price`) values ('Cake - Dulce De Leche', 58.02, 86.03);
insert into products (`name`, `purchase_price`, `sale_price`) values ('Nori Sea Weed', 49.48, 71.93);
insert into products (`name`, `purchase_price`, `sale_price`) values ('Beans - Green', 25.36, 94.88);
insert into products (`name`, `purchase_price`, `sale_price`) values ('Orange - Tangerine', 69.47, 66.18);
insert into products (`name`, `purchase_price`, `sale_price`) values ('Puree - Guava', 47.27, 52.12);
insert into products (`name`, `purchase_price`, `sale_price`) values ('Salami - Genova', 76.57, 42.51);
insert into products (`name`, `purchase_price`, `sale_price`) values ('Bar Mix - Lemon', 49.33, 94.93);
